### PR TITLE
Ft setup example add default interval

### PR DESCRIPTION
**Pull request by casparvv**
Adding a line with  ``interval: 1`` to planner.yaml seems to solve #27 for me.

### CODE REVIEW

**Comment by maxspahn** [comment]
Good catch! However, I think it would be better to assume `interval = 1` in case nothing is specified.

**Comment by casparvv** [comment]
> Good catch! However, I think it would be better to assume `interval = 1` in case nothing is specified.

Ahh indeed, in caseEvaluation.py then right?

**Comment by maxspahn** [comment]
What do you think of these changes?

**Review by casparvv — COMMENTED** [review]
Nice! Works for me.

**Comment by maxspahn** [comment]
I think the error is only present on the main branch. On `develop`, this problem is handled more generically. 
Could you for now test everything on `develop`. Soon there should be a first release on the main branch.

**Comment by casparvv** [comment]
Just tested the tutorial example on the `develop` branch and it works.
I should have checked that one first, my bad.

**Pull request closed without merging**
